name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.19.0'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev cppcheck

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c99 ../src/sensor_data.c
