name: C/C++ Analysis and Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure submodules (e.g., googletest) are initialized

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck build-essential

    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 --suppress=missingIncludeSystem .

    - name: Build and run tests
      run: |
        make clean
        make tests
        ./tests/test_main  # Run the GoogleTest executable
