name: C++ Build and Test with Memory Checking

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install g++ gcc

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Install Valgrind (for memory checking)
      run: sudo apt-get install valgrind

    - name: Build project
      run: make

    - name: Run tests with Valgrind
      run: make valgrind

    - name: Run tests with AddressSanitizer
      run: make asan
